[package]
distribution = "2201.9.2"
org = "ballerinax"
name = "openai.images"
version = "1.0.5"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = []
icon = "icon.png"
repository = "https://github.com/ballerina-platform/module-ballerinax-openai.images"

[build-options]
observabilityIncluded = true